/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcourseUpdateTitle } from './concourseUpdateTitle';
import type { ConcourseUpdateDescription } from './concourseUpdateDescription';
import type { ConcourseUpdateConstructionMemo } from './concourseUpdateConstructionMemo';

/**
 * Schema for updating a concourse.
 */
export interface ConcourseUpdate {
    title?: ConcourseUpdateTitle;
    description?: ConcourseUpdateDescription;
    construction_memo?: ConcourseUpdateConstructionMemo;
}
