/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum for Q-sort grid distribution enforcement.

forced — each column must hold exactly its declared capacity
    (Brown 1980; Watts & Stenner 2012).
free — total count must equal Q-set size; per-column capacities
    ignored at validation (Brown et al. 2015).
flexible — total enforced, per-column capacities are soft hints
    (warnings only). Qualis-specific compromise.
 */
export type DistributionMode = (typeof DistributionMode)[keyof typeof DistributionMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DistributionMode = {
    forced: 'forced',
    free: 'free',
    flexible: 'flexible',
} as const;
