/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { LogEntryContextAnyOf } from './logEntryContextAnyOf';

export type LogEntryContext = LogEntryContextAnyOf | null;
