/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Libre-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberRead } from './workspaceMemberRead';

export interface PaginatedResponseWorkspaceMemberRead {
    items: WorkspaceMemberRead[];
    total: number;
    limit: number;
    offset: number;
}
