/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Qualis API
 * OpenAPI spec version: 0.1.0
 */
import type { PublicConfigEmailDelivery } from './publicConfigEmailDelivery';
import type { PublicConfigAudioStorage } from './publicConfigAudioStorage';

/**
 * Minimal client bootstrap payload.

``email_delivery`` is "smtp" when SMTP credentials are configured and
"manual" otherwise (see docs/guides/running-without-smtp.md).

``audio_storage`` is "available" when S3/object-storage credentials are
configured and "unavailable" otherwise. When "unavailable", the
participant audio UI is suppressed and audio-enabled studies degrade to
text-only (see docs/guides/running-without-s3.md).
 */
export interface PublicConfig {
    email_delivery: PublicConfigEmailDelivery;
    audio_storage: PublicConfigAudioStorage;
}
