/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Open-Q API
 * OpenAPI spec version: 0.1.0
 */
import type { StatementUpdate } from './statementUpdate';

export type StudyUpdateStatements = StatementUpdate[] | null;
